import {
  Shirt,
  Home,
  Sparkles,
  Smartphone,
  Dumbbell,
  BookOpen,
  Gamepad2,
  Baby,
  Car,
  Utensils,
  Palette,
  Gift,
} from "lucide-react"
import type { Category } from "@/components/mega-menu"

export const megaMenuCategories: Category[] = [
  {
    name: "Fashion",
    href: "/products?category=fashion",
    icon: <Shirt className="h-5 w-5" />,
    image: "/category-clothing.png",
    featured: true,
    subcategories: [
      { name: "Women's Clothing", href: "/products?category=womens-clothing", featured: true },
      { name: "Men's Clothing", href: "/products?category=mens-clothing", featured: true },
      { name: "Accessories", href: "/products?category=accessories" },
      { name: "Jewelry & Watches", href: "/products?category=jewelry-watches" },
    ],
    promotion: {
      title: "Summer Collection 2023",
      description: "Discover our latest arrivals with up to 30% off on selected items.",
      image: "/promo-fashion.png",
      href: "/collections/summer-2023",
    },
  },
  {
    name: "Electronics",
    href: "/products?category=electronics",
    icon: <Smartphone className="h-5 w-5" />,
    image: "/category-electronics.png",
    subcategories: [
      { name: "Smartphones", href: "/products?category=smartphones", featured: true },
      { name: "Laptops & Computers", href: "/products?category=laptops-computers" },
      { name: "Audio & Headphones", href: "/products?category=audio-headphones" },
      { name: "Cameras & Photography", href: "/products?category=cameras-photography" },
    ],
    promotion: {
      title: "Tech Deals of the Week",
      description: "Save big on the latest gadgets and electronics with our weekly deals.",
      image: "/promo-electronics.png",
      href: "/collections/tech-deals",
    },
  },
  {
    name: "Home & Living",
    href: "/products?category=home-living",
    icon: <Home className="h-5 w-5" />,
    image: "/modern-home-decor.png",
    subcategories: [
      { name: "Furniture", href: "/products?category=furniture" },
      { name: "Home Decor", href: "/products?category=home-decor", featured: true },
      { name: "Kitchen & Dining", href: "/products?category=kitchen-dining" },
      { name: "Bedding & Bath", href: "/products?category=bedding-bath" },
    ],
  },
  {
    name: "Beauty & Personal Care",
    href: "/products?category=beauty-personal-care",
    icon: <Sparkles className="h-5 w-5" />,
    image: "/category-beauty.png",
    subcategories: [
      { name: "Skincare", href: "/products?category=skincare", featured: true },
      { name: "Makeup", href: "/products?category=makeup" },
      { name: "Haircare", href: "/products?category=haircare" },
      { name: "Fragrances", href: "/products?category=fragrances", new: true },
    ],
  },
  {
    name: "Sports & Outdoors",
    href: "/products?category=sports-outdoors",
    icon: <Dumbbell className="h-5 w-5" />,
    image: "/category-sports.png",
    subcategories: [
      { name: "Athletic Clothing", href: "/products?category=athletic-clothing" },
      { name: "Exercise Equipment", href: "/products?category=exercise-equipment" },
      { name: "Outdoor Recreation", href: "/products?category=outdoor-recreation", featured: true },
      { name: "Sports Accessories", href: "/products?category=sports-accessories" },
    ],
  },
  {
    name: "Books & Stationery",
    href: "/products?category=books-stationery",
    icon: <BookOpen className="h-5 w-5" />,
    image: "/category-books.png",
    subcategories: [
      { name: "Fiction & Literature", href: "/products?category=fiction-literature" },
      { name: "Non-Fiction", href: "/products?category=non-fiction" },
      { name: "Children's Books", href: "/products?category=childrens-books" },
      { name: "Stationery & Supplies", href: "/products?category=stationery-supplies", featured: true },
    ],
  },
  {
    name: "Toys & Games",
    href: "/products?category=toys-games",
    icon: <Gamepad2 className="h-5 w-5" />,
    image: "/category-toys.png",
    new: true,
    subcategories: [
      { name: "Action Figures & Collectibles", href: "/products?category=action-figures-collectibles" },
      { name: "Board Games", href: "/products?category=board-games", featured: true },
      { name: "Educational Toys", href: "/products?category=educational-toys" },
      { name: "Outdoor Play", href: "/products?category=outdoor-play" },
    ],
  },
  {
    name: "Baby & Kids",
    href: "/products?category=baby-kids",
    icon: <Baby className="h-5 w-5" />,
    subcategories: [
      { name: "Baby Clothing", href: "/products?category=baby-clothing" },
      { name: "Kids Fashion", href: "/products?category=kids-fashion", featured: true },
      { name: "Baby Gear", href: "/products?category=baby-gear" },
      { name: "Nursery", href: "/products?category=nursery" },
    ],
  },
  {
    name: "Automotive",
    href: "/products?category=automotive",
    icon: <Car className="h-5 w-5" />,
    subcategories: [
      { name: "Car Accessories", href: "/products?category=car-accessories", featured: true },
      { name: "Motorcycle Parts", href: "/products?category=motorcycle-parts" },
      { name: "Tools & Equipment", href: "/products?category=automotive-tools-equipment" },
      { name: "Car Care", href: "/products?category=car-care" },
    ],
  },
  {
    name: "Food & Grocery",
    href: "/products?category=food-grocery",
    icon: <Utensils className="h-5 w-5" />,
    subcategories: [
      { name: "Pantry Staples", href: "/products?category=pantry-staples" },
      { name: "Snacks & Sweets", href: "/products?category=snacks-sweets", featured: true },
      { name: "Beverages", href: "/products?category=beverages" },
      { name: "Organic & Natural", href: "/products?category=organic-natural", new: true },
    ],
  },
  {
    name: "Art & Crafts",
    href: "/products?category=art-crafts",
    icon: <Palette className="h-5 w-5" />,
    subcategories: [
      { name: "Drawing & Painting", href: "/products?category=drawing-painting", featured: true },
      { name: "Crafting", href: "/products?category=crafting" },
      { name: "Sewing & Fabric", href: "/products?category=sewing-fabric" },
      { name: "Art Supplies", href: "/products?category=art-supplies" },
    ],
  },
  {
    name: "Gifts & Special Occasions",
    href: "/products?category=gifts-special-occasions",
    icon: <Gift className="h-5 w-5" />,
    subcategories: [
      { name: "Birthday Gifts", href: "/products?category=birthday-gifts" },
      { name: "Anniversary Gifts", href: "/products?category=anniversary-gifts" },
      { name: "Wedding Gifts", href: "/products?category=wedding-gifts", featured: true },
      { name: "Holiday Gifts", href: "/products?category=holiday-gifts" },
    ],
  },
]
